#!/bin/bash

var=3

until [ $var -eq 0 ]
do
   echo "Outer loop: $var"
   var2=1
   while [ $var2 -lt 5 ]
   do
      var3=`echo "scale=4; $var / $var2" | bc`
      echo "Inner loop: $var / $var2 = $var3"
      var2=$[ $var2 + 1]
   done
   var=$[ $var - 1]
done
