#!/bin/bash

function testit {
  local newarray
  newarray=(`echo "$@"`)
  echo "The new array value is : ${newarray[*]}"
}

myarray=(1 2 3 4 5)
echo "The original array is ${myarray[*]}"
testit ${myarray[*]}

function addarray {
  local sum=0
  local newarray
  local oldarray
  local element
  local i
  oldarray=(`echo "$@"`)
  newarray=(`echo "$@"`)
  element=$[ $# - 1 ]
  for value in ${newarray[*]}
  do
     sum=$[ $sum + $value ]
  done
  echo $sum
  
  for (( i = 0;i <= $element; i++ ))
  {
     newarray[$i]=$[ ${oldarray[$i]} * 2 ]
  }
  echo ${[newarray[*]]}
}

myarray=(1 2 3 4 5)
echo "The original array is: ${myarray[*]}"
arg1=`echo ${myarray[*]}`
result=`addarray $arg1`
echo "The result is $result"
