#!/bin/bash

for var in 1 2 3 4 5 6 7 8 9 
do
   if [ $var -eq 5 ]
   then
      break
   fi
   echo "Iteration number: $var"
done
echo "The for loop is completed"

for (( a = 1;a < 4; a++))
do
  echo "Outer loop: $a"
  for (( b = 1;b<100;b++ ))
  do
     if [ $b -gt 4 ]
     then
         break 2
     fi
     echo "Inner loop: $b"
  done
done
