#!/bin/bash

function func1 {
  echo "This is an example of a function"
}

func2() {
  echo "Second function"
}

count=1
while [ $count -le 5 ]
do 
   func1
   count=$[ $count + 1 ]
done
echo "end of loop"
func2
echo "The end of the script"

function db1 {
  read -p "Enter a value: " value
  echo "doubling the value"
  return $[ $value * 2 ]
  #此值在0~255之间，否则$?无法提取
}
db1
echo "The new value is $?"

function db2 {
   echo "4"
}
result=`db2`
echo "The new value is $result"
