#!/bin/bash

#-n选项后面接数字，只接收1个参数，read命令就退出
read -n 1 -p "Do you want to continue [Y/N]?" answer
case $answer in
Y | y) echo
       echo "fine continue on...";;
N | n) echo
       echo OK,goodbye
       exit;;
esac
echo "This is the end of the script"
