#!/bin/bash

#将文件描述符3重定向到文件描述符1的当前位置，即STDOUT
#表明发送到文件描述符3的输出都出现在屏幕上
exec 3>&1
#将STDOUT重定向到一个文件。将发送到STDOUT的输出重定向到
#输出文件，但此时文件描述符3仍然指向屏幕
exec 1>test14out

echo "This should store in the output file"
echo "along with this line"

#将STDOUT重定向到文件描述符3的当前位置，即屏幕
exec 1>&3

echo "Now things should be back to normal"
