#!/bin/bash

#用文件描述符6保存STDIN位置
exec 6<&0
#将STDIN重定向到文件
exec 0< test1.cpp

count=1
#此时read命令的输入都来自于重定向后STDIN，即文件
while read line
do
   echo "Line #$count: $line"
   count=$[ $count + 1 ]
done
#将STDIN重定向到文件描述符6，设置回原来的位置
exec 0<&6
read -p "Are you done now? " answer
case $answer in
Y|y) echo "Goodbye";;
N|n) echo "Sorry,this is the end";;
esac
