#!/bin/bash

#mktemp -t参数在/tmp路径下创建临时文件
#mktemp -d dir.XXXXXX 参数创建临时目录
tempfile=`mktemp test19.XXXXXX`
exec 3>$tempfile

echo "This script writes to temp file $tempfile"

echo "This is the first line" >&3
echo "This is the second line" >&3
echo "This is the last line" >&3
exec 3>&-

echo "Done creating temp file.The contents are:"
cat $tempfile
rm -f $tempfile 2> /dev/null
